version: '3'

services:
  app:
    build:
      context: ./app
      dockerfile: Dockerfile
    volumes:
      - ./app:/app
      - ./prisma:/app/prisma
      - ./.env:/app/.env
      - node_modules_app:/app/node_modules
    ports:
      - "3000:3000"
    depends_on:
      - postgres

  subscriber:
    build:
      context: ./subscriber
      dockerfile: Dockerfile
    volumes:
      - ./subscriber:/app
      - ./prisma:/app/prisma
      - ./.env:/app/.env
      - node_modules_subscriber:/app/node_modules
    depends_on:
      - postgres

  postgres:
    image: postgres:15-bullseye
    logging:
      options:
        max-size: 10m
        max-file: "3"
    ports:
      - "5432:5432"
    expose:
      - "5432"
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=marketplace

volumes:
  node_modules_app:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ${PWD}/app/node_modules
  node_modules_subscriber:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ${PWD}/subscriber/node_modules
